// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.edu.ufcg.embedded.comercio.dominio;

import br.edu.ufcg.embedded.comercio.dominio.Produto;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Produto_Roo_Configurable {
    
    declare @type: Produto: @Configurable;
    
}
